### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by mikethreels**
### When creating the project the following points have been added
- [x]  setup Webpack for this repo
- [x] created one index.js file importing the different tabs from separate modules
- [x] kept the app logic separated from DOM manipulation
- [x] styled the pages using CSS

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello good work on your project 👍  
However your application has some problems.

# Changes Required 🔴 

- [x] There is an empty artifact on your TODO listing that is empty and cant be removed. This causes visual glitches. Please either remove or give a style if its meant to be used as a separator. 

- [x] You added validations to the form to create new TODOs however the item still gets created. Please fix your validations.

- [x] All of your forms have a border-radius but no padding to make up for it on the text. This causes visual glitches.

- [x] You are disabling the rule import/no-cycle for the linters, this rule give us an important feedback that you will have to follow on React or your application will have security breaches and/or crash. In general Circular dependencies are a bad practice. Lets fix that. Also if you need more info you might want to read this article: https://spin.atomicobject.com/2018/06/25/circular-dependencies-javascript/

# Optional Changes 🟡 

- [x] The general design is heavy and cluttered. You might want to see this examples of todo list apps:
https://raw.githubusercontent.com/ayazsayyed/vue-todo/master/dist/assets/img/dashboard.png
https://miro.medium.com/max/2732/1*VTKsiByHMcWDIxpFawp4fg.png
https://todoist.com/_next/static/images/screenshot@2x_ae827f4eb0a098f8926d48872079fd50.png
This is not a hard requirement and is optional however this project can be portfolio material I recommend you work harder on your presentation.

After making the requested changes feel free to resubmit your project for another review.

Cheers! 🥇

**Comment by mikethreels** [comment]
## Change Log

### The following changes have been made as suggested by the TSE
- [x] Cleaned up HTML so there are no empty elements
- [x] Fixed the validation which wasn't working
- [x] Added padding to the input forms 
- [x] Enabled  the rule import/no-cycle and fixed the bugs
- [x] Made the forms collapsable so the design is less cluttered.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @mikethreels 
### You have done well so far :clap: However, you have a minor issue to fix, add an edit feature to the todo item.
### Make the change and submit for another code review. Good luck.
- Happy coding!

**Comment by mikethreels** [comment]
## Change Log

### The following changes have been made as suggested by the TSE
- [x] added the edit button for the todo's
- [x] styled overflow and scrollbar

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Progress :clap: However, the suggested changes weren't fully implemented. It still shows errors when I edit a todo. Plus you didn't deploy the last version of the app :red_circle:  . When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by mikethreels** [comment]
## Change Log

### The following changes have been made as suggested by the TSE
- [x] fixed the bug mentioned by the TSE

NOTE: in case the next review is as fast as the previous one please give the live version a few minutes to update.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Michael. 👋

Good work on this. And it's a nice job attempting to fix the issue raised in the previous review.

 - [x] However, after editing a todo item it creates a new todo item rather than simply change features on the intended edited todo. Please fix it.

 - [x]  Kindly add an event.preventDefault() to your forms submissions methods.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by mikethreels** [comment]
## Change Log

### The following changes have been made as suggested by the TSE
- [x] added preventDefault()

**Comment by Dandush03** [comment]
# Status: :rocket: Project Approved :green_circle: 
Great work implementing all changes
### Good luck in your next project
# Happy Coding :tophat: :computer:

**Pull request merged**
